BENCHMARKS.md
README.md
export_test.go
map.go
map_test.go
mpmcqueue.go
rbmutex.go
util.go

* Adds concurrent map data structure
The code is rough on edges, I didn't do any performance analysis, and the implementation may contain some bugs, but this Map looks promising to me. Hopefully, this or something similar lands into Golang standard library.
The Map follows the interface of sync.Map. One important difference with sync.Map is that only string keys are supported. That's because Golang standard library does not expose the built-in hash functions for `interface{}` values.
Map uses a modified version of Cache-Line Hash Table (CLHT) data structure: https://github.com/LPD-EPFL/CLHT
CLHT is built around idea to organize the hash table in cache-line-sized buckets, so that on all modern CPUs update operations complete with at most one cache-line transfer. Also, Get operations …

Add CLHT based Map

---

map.go
map_test.go

The loop started with reloading the table which is not necessary. It's sufficient to spin over the current bucket entry and go ahead.

Reduce atomic snapshot retry loop size

---

map.go

This bug could lead to all goroutines falling asleep.

Fix sync.Cond misuse in Map resize

---

map_test.go

This way allocations won't be showing up in the benchmarks and more work will be put on the Map itself.

Remove string key allocations in Map benchmarks

---

README.md
counter.go
map.go
rbmutex.go
util.go

Closes #7
Refs #9 
* Replaces FNV-1a 32-bit function with faster built-in 64-bit memhash function which is internally used in Golang standard library.
* Change hash64 return type. It makes no sense to trim the returned result to uint32 in hash64. Moreover, that may make hash code distribution worse.

Replace FNV-1a with memhash in Map

---

export_test.go
map.go
map_test.go

Closes #2
* Removes linked lists from Map buckets
- Also increases bucket size to fit 7 entries (2 CLs). So, when compared with the current Map maximum number of entries in bucket decrease from 9 to 7 entries. On the other hand, spacial locality and data density improved
* Adds a cache with top bytes of entry hash codes
- Improves key lookup efficiency by caching one most significant byte of each map entry. This way string dereference and equality check is avoided for a significant portion of scanned entries
* Decreases the shrink threshold fraction proportionally to the new map layout
Here is the result of comparison with current `main` (v1.0.2) on my laptop (Ubuntu 20.04, i5-8300h, Go 1.17)
```bash
$ benchstat old.txt new.txt
name                      old time/op  new time/op  delta …
```

Remove bucket chaining from Map

---

map.go
map_test.go
mapof.go
mapof_test.go

The method docs for `LoadOrStore` mention:
> it stores and returns the given value
but the current implementation does not return the provided value when `!loaded`.
Maybe I'm overlooking something obvious? :thinking:

LoadOrStore: actually return the given value

---

.github/workflows/build.yml
map.go
map_test.go
mapof.go
mapof_test.go

Addresses https://github.com/puzpuzpuz/xsync/issues/5#issuecomment-1089936881
Also simplifies `doStore` methods

Remove obsolete docs on Map and MapOf shrink behavior

---

map.go
map_test.go
mapof.go
mapof_test.go

Thanks for such a useful package
In practice, it is common to store new values while getting old values, similar to `atomic.Value.Swap()`, so this feature is added.
**Requirements:**
```go
var (
a      atomic.Value
i      int
loaded bool
)
i = 1
v := a.Swap(i)
loaded = v != nil
if !loaded {
v = 1
}
fmt.Println(v, loaded) // 1, false
i = 2
v = a.Swap(i)
loaded = v != nil
fmt.Println(v, loaded) // 1, true
i = 3
v = a.Swap(i)
loaded = v != nil
fmt.Println(v, loaded) // 2, true
```
**Implementation:**
```go
m := NewMapOf[int]()
i := 1
v, loaded := m.LoadAndStore("foo", i)
fmt.Println(v, loaded) // 1, false
i = 2
v, loaded = m.LoadAndStore("foo", i)
fmt.Println(v, loaded) // 1, true
i = 3
v, loaded = m.LoadAndStore("foo", i)
fmt.Println(v, loaded) // 2, true
```
If you find it useful, please …

Add Map.LoadAndStore

---

map.go
mapof.go
util.go

Cast hash64 value to uint64 before doing operations

---

export_test.go
map.go
map_test.go
mapof.go
mapof_test.go
mpmcqueue.go

Reintroduces bucket chaining, so that the map can cope with poor quality hash functions. This is a required preliminary step for #46.

Combine top hash caching with bucket chaining

---

.github/workflows/build-1.17.yml
.github/workflows/build-32-bit.yml
.github/workflows/build.yml
.github/workflows/coverage.yml
map.go
map_test.go

Top hashes now include 2 bytes instead of a single byte which improves top hash look up efficiency

Reduce map bucket size to 1CL

---

example_test.go
map.go
mapof.go
mapof_test.go
util.go

This PR has two commits. The first is using maphash only as an implementation detail, without any API changes. The second commit makes the usage of `maphash` part of the API, which would simplify implementing good hash functions for custom types.

Use hash/maphash instead of go:linkname hacks

---

map_test.go

1M string/int entries:
```
$ go test -benchmem -run=^$ -bench Range
goos: linux
goarch: amd64
pkg: github.com/puzpuzpuz/xsync/v2
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkMapRange-8           	     158	   7411077 ns/op	       6 B/op	       0 allocs/op
BenchmarkMapRangeStandard-8   	      62	  18308102 ns/op	      11 B/op	       0 allocs/op
BenchmarkMapOfRange-8         	      82	  12645228 ns/op	       9 B/op	       0 allocs/op
PASS
ok  	github.com/puzpuzpuz/xsync/v2	10.727s
```
64 string/int entries:
```
$ go test -benchmem -run=^$ -bench Range
goos: linux
goarch: amd64
pkg: github.com/puzpuzpuz/xsync/v2
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkMapRange-8           	15090876	        76.98 ns/op	       0 B/op	       0 allocs/op …
```

Improve map Range benchmarks

---

README.md
counter.go
counter_test.go
rbmutex.go
util.go

* The number of stripes is now calculated dynamically based on the number of cores and GOMAXPROCS
* The performance is close enough to the old one with 64 stripes while the memory footprint is significantly lower and, what's also important, unlucky distribution isn't a problem anymore
Note: this is a breaking change due to the new `NewCounter` method.

Optimize Counter thread-to-stripe distribution

---

map.go
map_test.go
mapof.go
mapof_test.go
util.go

Benchmarks for `MapOf[int, int]` with 64 keys
Before:
```
BenchmarkIntegerMapOf_WarmUp/reads=100%-8         	170225940	         7.107 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntegerMapOf_WarmUp/reads=99%-8          	147592124	         8.331 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntegerMapOf_WarmUp/reads=90%-reads-8    	100000000	        11.09 ns/op	       1 B/op	       0 allocs/op
BenchmarkIntegerMapOf_WarmUp/reads=75%-reads-8    	78332457	        16.03 ns/op	       4 B/op	       0 allocs/op
```
After:
```
BenchmarkIntegerMapOf_WarmUp/reads=100%-8         	208831473	         5.325 ns/op	       0 B/op	       0 allocs/op
BenchmarkIntegerMapOf_WarmUp/reads=99%-8          	180287820	         6.516 ns/op	       0 B/op	       0 allocs/op …
```

Optimize MapOf integer hash function

---

BENCHMARKS.md
README.md
counter.go
rbmutex.go
rbmutex_test.go

* The number of reader slots is now calculated dynamically based on the number of cores and `GOMAXPROCS`
* The algorithm is now different from the vanilla BRAVO and unlucky thread-to-slot distribution isn't a problem anymore
Note: this is a breaking change due to the new `NewRBMutex` method.

Optimize RBMutex footprint and thread-to-slot distribution

---

export_mapof_test.go
export_test.go
map.go
map_test.go
mapof.go
mapof_test.go
util.go
util_mapof.go

* `MapOf`'s design is now quite different from the `Map`'s one. `MapOf` uses immutable entry structs, so there are less objects allocated on the heap and, thus, less GC pressure. There is also no need to store hash tops - the whole hash code is now stored in buckets. `sync.Mutex` is used instead of a in-house spin lock.
* Hand-made hash function is now used for integers. It's of mediocre quality, but the compiler inlines it more happily than `memhash64`.
Benchmarks for `MapOf[int, int]` with 1K entries. The change is very noticeable on such small maps and fixed size keys.
Before:
```bash
$ go test -run=^$ -bench IntegerMapOf_WarmUp
goos: linux
goarch: amd64
pkg: github.com/puzpuzpuz/xsync/v2
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkIntegerMapOf_WarmUp/reads=100%-8 …
```

New MapOf design

---

counter_test.go
map.go
map_test.go
mapof_test.go
rbmutex_test.go

Also removes map debug output from benchmark runs. The output can be seen in verbose test output now.

Report throughput in benchmarks

---

mapof.go

Before:
```
BenchmarkMapOfRange-8   	 1000000	      1283 ns/op	    779361 ops/s	       0 B/op	       0 allocs/op
```
After:
```
BenchmarkMapOfRange-8   	 1241162	       961.4 ns/op	   1040141 ops/s	       0 B/op	       0 allocs/op
```

Optimize MapOf.Range

---

export_test.go
map.go
map_test.go
mapof.go
mapof_test.go

Add presized constructors for Map and MapOf 

---

README.md
map.go
map_test.go
mapof.go
mapof_test.go

Reverts most of the changes from #45, but still gets rid of redundant allocations in `Range`.

Fix potential iteration over duplicate keys in Map/MapOf.Range

---

map.go
map_test.go
mapof.go
mapof_test.go

Fix lost updates on concurrent Map/MapOf resize

---

map.go
map_test.go
mapof.go
mapof_test.go

Fix too agressive Map/MapOf shrinking on deletion leading to out of range panic

---

example_test.go
export_test.go
map.go
map_test.go
mapof.go
mapof_test.go

Closes #103
Closes #119
Refs #116, #118
Also, `NewMapPresized`/`NewMapOfPresized`'s argument is now treated as the minimal table capacity. The underlying hash table won't shrink beyond the specified capacity.

Use presized Map/MapOf argument as the minimal map capacity

---

export_test.go
map.go
map_test.go
mapof.go
mapof_test.go

Adds options support to the `NewMap`/`NewMapOf` functions. A `MapOf` can now be created like this:
```go
m := xsync.NewMapOf(WithPresize(100))
```
Also, adds `WithGrowOnly` option. It configures new Map/MapOf instance to be grow-only. This means that the underlying hash table grows in capacity when new keys are added, but does not shrink when keys are deleted. The only exception to this rule is the Clear method which shrinks the hash table back to the initial capacity.
Grow-only maps are more efficient in the case of oscillating map size, i.e. when the map frequently grows and then shrinks in size.

Introduce Map/MapOf configs and grow-only option

---

export_test.go
map.go
map_test.go
mapof.go
mapof_test.go

Map/MapOf statistics are available via `m.Stats()`. They may be used for diagnostic purposes.

Expose Map/MapOf statistics

---

BENCHMARKS.md
README.md
export_test.go
map.go
mapof.go
mapof_test.go
util.go
util_test.go

Introduces meta memory and SWAR-based lookups similar to C++'s `absl::flat_hash_map` hash table (https://abseil.io/docs/cpp/guides/container).
Also, reduces `MapOf`'s memory overhead: each bucket now holds up to 5 entries instead of 3.
A few benchmark results were collected on a laptop with i7-1185G7 and 32GB RAM running Ubuntu 22.04.
Before:
```
BenchmarkMapOfInt_WarmUp/reads=100%-8         	303130814	         4.131 ns/op	 242101267 ops/s	       0 B/op	       0 allocs/op
BenchmarkMapOfInt_WarmUp/reads=99%-8          	232482326	         5.196 ns/op	 192442573 ops/s	       0 B/op	       0 allocs/op
BenchmarkMapOfInt_WarmUp/reads=90%-8          	180387648	         6.811 ns/op	 146829029 ops/s	       0 B/op	       0 allocs/op
BenchmarkMapOfInt_WarmUp/reads=75%-8          	129619245 …
```

WIP better MapOf

---

export_test.go
mapof.go
mapof_test.go
util_hash.go
util_hash_test.go

Adds `NewMapOfWithHasher` function to support custom hash functions:
```go
m := NewMapOfWithHasher[int, int](func(i int, _ uint64) uint64 {
// Murmur3 finalizer. No DDOS protection as it does not support seed.
h := uint64(i)
h = (h ^ (h >> 33)) * 0xff51afd7ed558ccd
h = (h ^ (h >> 33)) * 0xc4ceb9fe1a85ec53
return h ^ (h >> 33)
})
```
Some custom hash functions may be faster than the built-in function if the lack of DDOS protection is fine.
Murmur3 finalizer:
```bash
BenchmarkMapOfInt_Murmur3Finalizer_WarmUp/reads=100%-8         	525864650	         2.240 ns/op	 446360938 ops/s	       0 B/op	       0 allocs/op
BenchmarkMapOfInt_Murmur3Finalizer_WarmUp/reads=99%-8          	383333918	         3.127 ns/op	 319827294 ops/s	       0 B/op	       0 allocs/op …
```

Add NewMapOfWithHasher function

---

README.md
map.go
map_test.go
mapof.go
mapof_test.go

Also fixes `NewMapOfWithHasher`'s godoc and improves the readme.

Fix Map/MapOf capacity calculation for WithPresize

---

rbmutex.go

Attempt at adding `RBMutex.TryRLock` that tries to retrieve a reader lock token via the fast path or gives up returning nil.

Add RBMutex.TryRLock

---

README.md
map.go
map_test.go
mapof.go
mpmcqueue.go
mpmcqueue_test.go
mpmcqueueof.go
mpmcqueueof_test.go
spscqueue.go
spscqueue_test.go
spscqueueof.go
spscqueueof_test.go

Also deprecates `MPMCQueue`/`MPMCQueueOf`'s blocking methods

Add SPSCQueue/SPSCQueueOf

---

map.go
map_test.go
mapof.go
mapof_test.go
spscqueue.go
spscqueueof.go

Add LoadOrTryCompute method to Map/MapOf

---

map.go
mapof.go

The existing docs seem to be derived from `LoadOrStore`, and reference what happens when a value is "stored". It would be clearer if the docs used consistent terminology and discussed what happens when a value is "computed".

Clarify docs for `LoadOrCompute` and `LoadOrTryCompute`

---

README.md
example_test.go
export_test.go
map.go
map_test.go
mpmcqueueof.go
mpmcqueueof_test.go
spscqueueof.go
spscqueueof_test.go

See https://github.com/puzpuzpuz/xsync/pull/163#discussion_r2020419080 for more details. This new major version can be used to rename `MapOf` to `Map`.

Rename and deprecate `*Of` types

---

export_test.go
map.go
map_test.go

Using `unsafe.Pointer` has obvious pitfalls, but was effectively required before the introduction of `atomic.Pointer`. So this code replaces that, and generally cleans up usage of `atomic.Load`, since it's discouraged in favor of `atomic.Pointer`. This change replaces pretty much all usages of it for `Map` (not the other data structures).
The benchmark results indicate that this has no performance impact, which is expected since the code is semantically unchanged.
```
goos: linux
goarch: amd64
pkg: github.com/puzpuzpuz/xsync/v4
cpu: AMD EPYC 7763 64-Core Processor
│   unsafe    │                safe                │
│   sec/op    │   sec/op     vs base               │
Map_NoWarmUp/reads=99%-8      7.974n ± 3%   8.069n ± 1%  +1.20% (p=0.014 n=10)
Map_NoWarmUp/reads=90%-8      10.59n ± 3% …
```

Remove usage of `unsafe.Pointer` in `Map` wherever possible

---

map.go

We can see improvements in both `LoadOrStore` and `Delete`, mainly due to the reuse of hash computations and other optimizations, accounting for both loading and deletion scenarios (with many repeated deletions). 
It seems the `doLoadOrCompute` function might not be necessary.
| Operation       | Implementation | 1 Record (ns/op) | 1M Records (ns/op) | 1B Records (ns/op) | Allocs/op (1B) |
|-----------------|----------------|------------------|--------------------|--------------------|----------------|
| **Store**       | xsync.MapOf    | 149.8            | 11.17              | 11.72              | 1              |
|                 | Map            | 153.0            | 11.40              | 11.61              | 1              |
| **LoadOrStore** | xsync.MapOf    | 0.3243           | 9.533 …

Replace doLoadOrCompute with a read-only path in doCompute

---

map.go

This commit enables the map to conditionally trigger parallel copying during resize, directly improving the performance of all write operations. Compared to other optimization methods, parallel resize is well-suited for the current map implementation. Here's a comparison:
1. **Incremental COW**: Lower overall throughput compared to parallel resize, non-conflicting logic but more complex code.
2. **Moving Mutex outside buckets**: Reduces lock false sharing, decreases write performance, improves read performance.
3. **Spinlock**: A more aggressive version of 2, significantly reduces lock false sharing, greatly boosts load performance, but carries some risks.
4. **Using a faster Go built-in hash**: A hacky approach that leverages Go's built-in keyHash and valEqual functions for slightly …

Parallel Map resize

---

README.md
export_test.go
map.go
map_test.go
util.go

Introduces cooperative rehashing for `xsync.Map` this means that goroutines that execute write operations, such as `Compute` or `Store`, may participate in table rehashing when the hash table grows or shrinks.
This behavior is always enabled, so the `WithSerialResize` function now acts as a no-op and is marked as deprecated.
This patch:
```
BenchmarkMapParallelRehashing/1goroutine_10M-24         	       1	2133256824 ns/op	   4775648 entries/s	754307064 B/op	10895782 allocs/op
BenchmarkMapParallelRehashing/4goroutines_10M-24        	       2	 695167535 ns/op	  14953777 entries/s	754273520 B/op	10896557 allocs/op
BenchmarkMapParallelRehashing/8goroutines_10M-24        	       2	 530385413 ns/op	  20218249 entries/s	754222912 B/op	10895744 allocs/o
```
`main` (shows similar performance, but …

Cooperative rehashing in Map

---

counter_test.go
map.go
map_test.go
mpmcqueue_test.go
rbmutex_test.go
spscqueue_test.go
umpscqueue_test.go
util_test.go

This small MR is just the result of calling modernize[0] on the codebase.
It does have some effect on the benchmarks, though: the new b.Loop() way of disables more optimizations and so causes "worse" benchmark results, though I'd say they are more realistic. WDYT?
[0] https://golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize

chore: modernize for go 1.24
